name: Staging Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main # Check out main instead of the latest commit.
          fetch-depth: 0 # Fetch all history, since deploy is Git based.

      - name: Set up Python dependency
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.1

      - name: Deploy to Gigalixir
        uses: mhanberg/gigalixir-action@v0.6.1
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: ${{ secrets.GIGALIXIR_APP }}
          SSH_PRIVATE_KEY: ${{ secrets.GIGALIXIR_SSH_PRIVATE_KEY }}
