name: Deploy to EC2 prod

on:
  push:
    branches: ["release"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            cd /var/www/html/db-service-prod/ &&
            sudo rm /var/www/html/db-service-prod/priv/static/swagger.json &&
            sudo git pull origin release &&
            sudo MIX_ENV=prod mix deps.get &&
            sudo MIX_ENV=prod mix deps.compile &&
            sudo MIX_ENV=prod mix ecto.migrate &&
            sudo MIX_ENV=prod mix phx.swagger.generate &&
            sudo MIX_ENV=prod elixir --erl "-detached" -S mix phx.server

          '
