name: Deploy to EC2 staging

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            cd /var/www/html
            sudo ./kill_process_on_port_4000.sh
            cd /var/www/html/db-service &&
            sudo git checkout . &&
            if [ -f /var/www/html/db-service/priv/static/swagger.json ]; then
              sudo rm /var/www/html/db-service/priv/static/swagger.json
            fi
            sudo git pull origin \"$branch_name\" &&
            sudo MIX_ENV=prod mix deps.get &&
            sudo MIX_ENV=prod mix deps.compile &&
            sudo MIX_ENV=prod mix ecto.migrate &&
            sudo MIX_ENV=prod mix phx.swagger.generate &&
            sudo MIX_ENV=prod elixir --erl "-detached" -S mix phx.server
          "
