name: Deploy to EC2 staging

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            sudo su &&
            cd /var/www/html/db-service &&
            sudo git pull origin "$branch_name" &&
            sudo MIX_ENV=prod mix deps.get &&
            sudo MIX_ENV=prod mix deps.compile &&
            sudo MIX_ENV=prod mix ecto.migrate &&
            sudo MIX_ENV=prod mix phx.swagger.generate
          '
