name: Deploy to EC2 staging

on:
  push:
    branches: 
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Extract branch name
          shell: bash
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          id: extract_branch
      
      - name: Deploy in EC2
        env:
          BASTION_HOST_PRIVATE_KEY: ${{ secrets.STAGING_BASTION_HOST_PRIVATE_KEY }}
          BRANCH_NAME_TO_DEPLOY: ${{ steps.extract_branch.outputs.branch }}
          BASTION_HOST_INSTANCE_NAME: "staging-DB-Bastion-Host"
          TARGET_GROUP_NAME: "staging-DB-lb-alb-tg"
          ENVIRONMENT_PREFIX: "staging-DB-"

      - name: Run Deployment Script
        run: |
          bash deployment/runOnGithubAction.sh
